project:
  type: website 
  title: "AMBR"

website: 
  body-header: "Practical materials for Advanced Methods in Behavioural Research, Semester 2 (2025-2026), University of York."
  page-footer: 
    center:
      - text: "License"
        href: LICENSE.md
  navbar:
    search: true
    pinned: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Set-up guide"
        href: ambr0_guide.qmd
      - text: "Weekly content"
        menu: 
        - text: "W1: Meta-analysis"
          href: ambr1_meta-analysis.qmd
          

format: 
  html: 
    theme: united
    title-block-banner: true
    toc: true
    toc-location: left
    toc-title: "Outline"
    toc-depth: 2
    toc-expand: 2
    number-sections: true
    link-external-newwindow: true 
  pdf: 
    number-sections: true
    number-depth: 3
    format: 
      papersize: a4
      fontfamily: "Verdana"
    geometry:
      - top=25mm
      - bottom=25mm
      - left=20mm
      - right=20mm
  docx: 
    number-sections: true
    number-depth: 3
    page-width: 8.27
    

execute: 
  freeze: auto