project:
  type: website 
  title: "AMBR"

website: 
  sidebar:
    style: "docked"
    search: true
    contents: 
      - section: "Week 1: Meta-analysis"
        href: ambr1_meta-analysis.qmd

format: 
  html: 
    theme: lumen
    title-block-banner: true
    toc: true
    toc-location: left
    toc-depth: 4
    toc-expand: true
  pdf: 
    number-sections: true
    number-depth: 3
    format: 
      papersize: a4
      fontfamily: "Verdana"
    geometry:
      - top=25mm
      - bottom=25mm
      - left=20mm
      - right=20mm
  docx: 
    number-sections: true
    number-depth: 3
    page-width: 8.27
    

execute: 
  freeze: auto